Updated file names... docs next

diff --git a/bin/bedrock_activate_release b/bin/bedrock_activate_release
--- a/bin/bedrock_activate_release
+++ b/bin/bedrock_activate_release
@@ -8,7 +8,7 @@ REQUESTED_VERSION=$1
   REQUESTED_VERSION=$(bedrock_current_release)
 }
 
-bin/bedrock_release_installed "${REQUESTED_VERSION}" || {
+bin/bedrock_installed_release "${REQUESTED_VERSION}" || {
   bin/bedrock_install_release "${REQUESTED_VERSION}" || {
     echo "Could not install ${REQUESTED_VERSION}"
     exit 1
@@ -19,20 +19,20 @@ REQUESTED_INSTALL="${INSTALL_BASE}/${REQUESTED_VERSION}"
 
 # Ensure the server is stopped
 bin/bedrock_server_running && {
-  echo "Stopping running bedrock-server"
+  echo "Stopping running ${BEDROCK_SERVICE}"
   bin/bedrock_stop_server
   bin/bedrock_server_running && {
-    echo "Could not stop bedrock-server"
+    echo "Could not stop ${BEDROCK_SERVICE}"
     exit 1
   }
 }
 
-echo "Demoting ${CURRENT_INSTALL} to ${PREVIOUS_INSTALL}"
-mv "${CURRENT_INSTALL}" "${PREVIOUS_INSTALL}"
+echo "Demoting ${SELECTED_INSTALL} to ${PREVIOUS_INSTALL}"
+mv "${SELECTED_INSTALL}" "${PREVIOUS_INSTALL}"
 
-echo "Activating ${REQUESTED_INSTALL} as ${CURRENT_INSTALL}"
-ln -s "${REQUESTED_INSTALL}" "${CURRENT_INSTALL}" || {
-  echo "Could not activate as ${CURRENT_INSTALL}"
+echo "Activating ${REQUESTED_INSTALL} as ${SELECTED_INSTALL}"
+ln -s "${REQUESTED_INSTALL}" "${SELECTED_INSTALL}" || {
+  echo "Could not activate as ${SELECTED_INSTALL}"
   exit 1
 }
 
diff --git a/bin/bedrock_install_release b/bin/bedrock_install_release
--- a/bin/bedrock_install_release
+++ b/bin/bedrock_install_release
@@ -20,11 +20,11 @@ REQUESTED_ARCHIVE="${REQUESTED_INSTALL}.zip"
 }
 
 # Existing Install
-[ -e "${CURRENT_INSTALL}" ] && {
-  [ "$(readlink ${CURRENT_INSTALL})" == "${REQUESTED_INSTALL}" ] || {
-    echo "Using ${CURRENT_INSTALL} as Installation base"
+[ -e "${SELECTED_INSTALL}" ] && {
+  [ "$(readlink ${SELECTED_INSTALL})" == "${REQUESTED_INSTALL}" ] || {
+    echo "Using ${SELECTED_INSTALL} as Installation base"
     bin/bedrock_clone_server_as "${REQUESTED_VERSION}" || {
-      echo "Could not copy ${CURRENT_INSTALL} to ${REQUESTED_INSTALL}"
+      echo "Could not copy ${SELECTED_INSTALL} to ${REQUESTED_INSTALL}"
     }
   }
 }
diff --git a/bin/bedrock_start_services b/bin/bedrock_start_services
--- a/bin/bedrock_start_services
+++ b/bin/bedrock_start_services
@@ -1,7 +1,12 @@
 #!/bin/bash
 source ~/.config/bedrock_server.config
-
-for SERVICE in ${START_SERVICES}; do
+for TIMER in ${AUTO_TIMERS}; do
+  systemctl --user enable "${TIMER}" &> /dev/null || {
+    echo "Could not enable ${TIMER}"
+    exit 1
+  }
+done
+for SERVICE in ${AUTO_SERVICES}; do
   systemctl --user is-active "${SERVICE}" &> /dev/null || {
     echo "Starting ${SERVICE}"
     systemctl --user start "${SERVICE}"
diff --git a/bin/bedrock_stop_services b/bin/bedrock_stop_services
--- a/bin/bedrock_stop_services
+++ b/bin/bedrock_stop_services
@@ -1,7 +1,13 @@
 #!/bin/bash
 source ~/.config/bedrock_server.config
+for TIMER in ${AUTO_TIMERS}; do
+  systemctl --user disable "${TIMER}" &> /dev/null || {
+    echo "Could not disable ${TIMER}"
+    exit 1
+  }
+done
 
-for SERVICE in ${START_SERVICES}; do
+for SERVICE in ${AUTO_SERVICES}; do
   systemctl --user is-active "${SERVICE}" &> /dev/null && {
     echo "Stopping ${SERVICE}"
     systemctl --user stop "${SERVICE}" || {
